cloud:
  aws:
    credentials:
      access-key: ${access-key}
      secret-key: ${secret-key}
    s3:
      profile-bucket: ${profile-bucket}
      album-bucket: ${album-bucket}
    region:
      static: ${region}
    stack:
      auto: false

server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/kkanggogoalbum?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false


logging:
  level:
    root: debug