name: CI/CD
on:
  push:
    branches: [detach_builds]
  pull_request:
    branches: [main]

jobs:
  FrontEndBuild:
    name: Build Frontend
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend/face_album
    strategy:
      matrix:
        node-version: [ 14.15.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: npm ci
        working-directory: ${{ env.working-directory }}

  CICD:
    name: CI/CD with Gradle
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: FrontEndBuild

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build

      - name: Before deply
        run: |
          mkdir -p before-deploy
          cp scripts/*.sh before-deploy/
          cp appspec.yml before-deploy/
          cp build/libs/*SNAPSHOT.jar before-deploy/
          cd before-deploy && zip -r before-deploy *
          cd ../ && mkdir -p deploy
          mv before-deploy/before-deploy.zip deploy/facealbum-springboot-server.zip

      - name: AWS config
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to AWS S3
        run: aws s3 cp deploy/facealbum-springboot-server.zip s3://faceablum-springboot-build

      - name: Codedeploy
        run: aws deploy create-deployment --application-name facealbum-springboot-server --deployment-group-name facealbum-springboot-server-group --s3-location bucket=faceablum-springboot-build,bundleType=zip,key=facealbum-springboot-server.zip

